config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "logins#new"
  get "login/create", to: "logins#create", as: :create_login
  get "/dashboard", to: "users#show", as: :dashboard

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  end

  def create
    if user = authenticate_with_google
      cookies.signed[:user_id] = user.id
      redirect_to dashboard_path
    else
      redirect_to login_path, alert: 'authentication_failed'
    end
  end

  private

  def authenticate_with_google
    if id_token = flash["google_sign_in"]["id_token"]
      google_identity = GoogleSignIn::Identity.new(id_token)
      User.find_or_initialize_by(google_id: google_identity.user_id).tap do |u|
        u.email = google_identity.email_address
        u.email_verified = google_identity.email_verified?
        u.avatar_url = google_identity.avatar_url
        u.save
      end
    elsif error = flash[:google_sign_in][:error]
      logger.error "Google authentication error: #{error}"
      nil
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalendarSync</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/logins/new.html.erb
<main class="login-page justify-content-center mt-4 d-flex">
  <div data-turbo="false" class="login-button">
    <%= google_sign_in_button image_tag('google_logo.png', alt: 'Google'), proceed_to: create_login_url, class: "login-button" %>
  </div>
</main>

app/views/users/show.html.erb
<h2>Dashboard</h2>